export const ADD_NOT_ALLOCATED_REQUEST = "ADD_NOT_ALLOCATED_REQUEST";
export const ADD_NOT_ALLOCATED_SUCCESS = "ADD_NOT_ALLOCATED_SUCCESS";
export const ADD_NOT_ALLOCATED_FAILURE = "ADD_NOT_ALLOCATED_FAILURE";

export const GET_NOT_ALLOCATED_REQUEST = "GET_NOT_ALLOCATED_REQUEST";
export const GET_NOT_ALLOCATED_SUCCESS = "GET_NOT_ALLOCATED_SUCCESS";
export const GET_NOT_ALLOCATED_FAILURE = "GET_NOT_ALLOCATED_FAILURE";
