export const ADD_SUITABLE_CONSECUTIVESESSION_REQUEST =
  "ADD_SUITABLE_CONSECUTIVESESSION_REQUEST";
export const ADD_SUITABLE_CONSECUTIVESESSION_SUCCESS =
  "ADD_SUITABLE_CONSECUTIVESESSION_SUCCESS";
export const ADD_SUITABLE_CONSECUTIVESESSION_FAILURE =
  "ADD_SUITABLE_CONSECUTIVESESSION_FAILURE";
