export const ADD_YEAR_SEMISTER_REQUEST="ADD_YEAR_SEMISTER_REQUEST";
export const ADD_YEAR_SEMISTER_SUCCESS="ADD_YEAR_SEMISTER_SUCCESS";
export const ADD_YEAR_SEMISTER_FAILURE="ADD_YEAR_SEMISTER_FAILURE";
