export const ADD_SUITABLE_GROUPID_REQUEST = "ADD_SUITABLE_GROUPID_REQUEST";
export const ADD_SUITABLE_GROUPID_SUCCESS = "ADD_SUITABLE_GROUPID_SUCCESS";
export const ADD_SUITABLE_GROUPID_FAILURE = "ADD_SUITABLE_GROUPID_FAILURE";
