export const ADD_GEN_GROUPID_REQUEST = "ADD_GEN_GROUPID_REQUEST";
export const ADD_GEN_GROUPID_SUCCESS = "ADD_GEN_GROUPID_SUCCESS";
export const ADD_GEN_GROUPID_FAILURE = "ADD_GEN_GROUPID_FAILURE";

export const GET_GEN_GROUPID_REQUEST = "GET_GEN_GROUPID_REQUEST";
export const GET_GEN_GROUPID_SUCCESS = "GET_GEN_GROUPID_SUCCESS";
export const GET_GEN_GROUPID_FAILURE = "GET_GEN_GROUPID_FAILURE";
