export const ADD_RESERVED_TIME_REQUEST = "ADD_RESERVED_TIME_REQUEST";
export const ADD_RESERVED_TIME_SUCCESS = "ADD_RESERVED_TIME_SUCCESS";
export const ADD_RESERVED_TIME_FAILURE = "ADD_RESERVED_TIME_FAILURE";
