export const ADD_LECTURER_REQUEST="ADD_LECTURER_REQUEST";
export const ADD_LECTURER_SUCCESS="ADD_LECTURER_SUCCESS";
export const ADD_LECTURER_FAILURE="ADD_LECTURER_FAILURE";

export const GET_LECTURER_REQUEST = "GET_LECTURER_REQUEST";
export const GET_LECTURER_SUCCESS = "GET_LECTURER_SUCCESS";
export const GET_LECTURER_FAILURE = "GET_LECTURER_FAILURE";

export const UPDATE_LECTURER_REQUEST = "UPDATE_LECTURER_REQUEST";
export const UPDATE_LECTURER_SUCCESS = "UPDATE_LECTURER_SUCCESS";
export const UPDATE_LECTURER_FAILURE = "UPDATE_LECTURER_FAILURE";

export const GET_ONE_LECTURER_REQUEST = "GET_ONE_LECTURER_REQUEST";
export const GET_ONE_LECTURER_SUCCESS = "GET_ONE_LECTURER_SUCCESS";
export const GET_ONE_LECTURER_FAILURE = "GET_ONE_LECTURER_FAILURE";