export const ADD_CONSECUTIVE_SESSION_REQUEST =
  "ADD_CONSECUTIVE_SESSION_REQUEST";
export const ADD_CONSECUTIVE_SESSION_SUCCESS =
  "ADD_CONSECUTIVE_SESSION_SUCCESS";
export const ADD_CONSECUTIVE_SESSION_FAILURE =
  "ADD_CONSECUTIVE_SESSION_FAILURE";

export const GET_CONSECUTIVE_SESSION_REQUEST =
  "GET_CONSECUTIVE_SESSION_REQUEST";
export const GET_CONSECUTIVE_SESSION_SUCCESS =
  "GET_CONSECUTIVE_SESSION_SUCCESS";
export const GET_CONSECUTIVE_SESSION_FAILURE =
  "GET_CONSECUTIVE_SESSION_FAILURE";
