export const ADD_LOCATIONTIMETABLE_REQUEST = "ADD_LOCATIONTIMETABLE_REQUEST";
export const ADD_LOCATIONTIMETABLE_SUCCESS = "ADD_LOCATIONTIMETABLE_SUCCESS";
export const ADD_LOCATIONTIMETABLE_FAILURE = "ADD_LOCATIONTIMETABLE_FAILURE";

export const GET_LOCATIONTIMETABLE_REQUEST = "GET_LOCATIONTIMETABLE_REQUEST";
export const GET_LOCATIONTIMETABLE_SUCCESS = "GET_LOCATIONTIMETABLE_SUCCESS";
export const GET_LOCATIONTIMETABLE_FAILURE = "GET_LOCATIONTIMETABLE_FAILURE";
