export const ADD_SUITABLE_SESSION_REQUEST = "ADD_SUITABLE_SESSION_REQUEST";
export const ADD_SUITABLE_SESSION_SUCCESS = "ADD_SUITABLE_SESSION_SUCCESS";
export const ADD_SUITABLE_SESSION_FAILURE = "ADD_SUITABLE_SESSION_FAILURE";
