export const ADD_PREFERED_ROOM_REQUEST = "ADD_PREFERED_ROOM_REQUEST";
export const ADD_PREFERED_ROOM_SUCCESS = "ADD_PREFERED_ROOM_SUCCESS";
export const ADD_PREFERED_ROOM_FAILURE = "ADD_PREFERED_ROOM_FAILURE";
