export const ADD_SUITABLE_ROOM_REQUEST = "ADD_SUITABLE_ROOM_REQUEST";
export const ADD_SUITABLE_ROOM_SUCCESS = "ADD_SUITABLE_ROOM_SUCCESS";
export const ADD_SUITABLE_ROOM_FAILURE = "ADD_SUITABLE_ROOM_FAILURE";
