export const ADD_PARALLEL_SESSION_REQUEST = "ADD_PARALLEL_SESSION_REQUEST";
export const ADD_PARALLEL_SESSION_SUCCESS = "ADD_PARALLEL_SESSION_SUCCESS";
export const ADD_PARALLEL_SESSION_FAILURE = "ADD_PARALLEL_SESSION_FAILURE";

export const GET_PARALLEL_SESSION_REQUEST = "GET_PARALLEL_SESSION_REQUEST";
export const GET_PARALLEL_SESSION_SUCCESS = "GET_PARALLEL_SESSION_SUCCESS";
export const GET_PARALLEL_SESSION_FAILURE = "GET_PARALLEL_SESSION_FAILURE";
