export const ADD_GROUPID_REQUEST = "ADD_GROUPID_REQUEST";
export const ADD_GROUPID_SUCCESS = "ADD_GROUPID_SUCCESS";
export const ADD_GROUPID_FAILURE = "ADD_GROUPID_FAILURE";

export const GET_GROUPID_REQUEST = "GET_GROUPID_REQUEST";
export const GET_GROUPID_SUCCESS = "GET_GROUPID_SUCCESS";
export const GET_GROUPID_FAILURE = "GET_GROUPID_FAILURE";

export const UPDATE_GROUPID_REQUEST = "UPDATE_GROUPID_REQUEST";
export const UPDATE_GROUPID_SUCCESS = "UPDATE_GROUPID_SUCCESS";
export const UPDATE_GROUPID_FAILURE = "UPDATE_YEAR_SEMISTER_FAILURE";

export const GET_ONE_GROUPID_REQUEST = "GET_ONE_GROUPID_REQUEST";
export const GET_ONE_GROUPID_SUCCESS = "GET_ONE_GROUPID_SUCCESS";
export const GET_ONE_GROUPID_FAILURE = "GET_ONE_GROUPID_FAILURE";
