export const ADD_SUITABLE_LECTURER_REQUEST = "ADD_SUITABLE_LECTURER_REQUEST";
export const ADD_SUITABLE_LECTURER_SUCCESS = "ADD_SUITABLE_LECTURER_SUCCESS";
export const ADD_SUITABLE_LECTURER_FAILURE = "ADD_SUITABLE_LECTURER_FAILURE";
