export const ADD_TAG_REQUEST = "ADD_TAG_REQUEST";
export const ADD_TAG_SUCCESS = "ADD_TAG_SUCCESS";
export const ADD_TAG_FAILURE = "ADD_TAG_FAILURE";

export const GET_TAG_REQUEST = "GET_TAG_REQUEST";
export const GET_TAG_SUCCESS = "GET_TAG_SUCCESS";
export const GET_TAG_FAILURE = "GET_TAG_FAILURE";

export const UPDATE_TAG_REQUEST = "UPDATE_TAG_REQUEST";
export const UPDATE_TAG_SUCCESS = "UPDATE_TAG_SUCCESS";
export const UPDATE_TAG_FAILURE = "UPDATE_TAG_FAILURE";

export const GET_ONE_TAG_REQUEST = "GET_ONE_TAG_REQUEST";
export const GET_ONE_TAG_SUCCESS = "GET_ONE_TAG_SUCCESS";
export const GET_ONE_TAG_FAILURE = "GET_ONE_TAG_FAILURE";
