export const ADD_ROOM_REQUEST = "ADD_ROOM_REQUEST";
export const ADD_ROOM_SUCCESS = "ADD_ROOM_SUCCESS";
export const ADD_ROOM_FAILURE = "ADD_ROOM_FAILURE";

export const GET_ROOM_REQUEST = "GET_ROOM_REQUEST";
export const GET_ROOM_SUCCESS = "GET_ROOM_SUCCESS";
export const GET_ROOM_FAILURE = "GET_ROOM_FAILURE";

export const UPDATE_ROOM_REQUEST = "UPDATE_ROOM_REQUEST";
export const UPDATE_ROOM_SUCCESS = "UPDATE_ROOM_SUCCESS";
export const UPDATE_ROOM_FAILURE = "UPDATE_YEAR_SEMISTER_FAILURE";

export const GET_ONE_ROOM_REQUEST = "GET_ONE_ROOM_REQUEST";
export const GET_ONE_ROOM_SUCCESS = "GET_ONE_ROOM_SUCCESS";
export const GET_ONE_ROOM_FAILURE = "GET_ONE_ROOM_FAILURE";
