export const ADD_WORKINGDAYS_REQUEST="ADD_WORKINGDAYS_REQUEST";
export const ADD_WORKINGDAYS_SUCCESS="ADD_WORKINGDAYS_SUCCESS";
export const ADD_WORKINGDAYS_FAILURE="ADD_WORKINGDAYS_FAILURE";

export const GET_WORKINGDAYS_REQUEST = "GET_WORKINGDAYS_REQUEST";
export const GET_WORKINGDAYS_SUCCESS = "GET_WORKINGDAYS_SUCCESS";
export const GET_WORKINGDAYS_FAILURE = "GET_WORKINGDAYS_FAILURE";


export const UPDATE_WORKINGDAYS_REQUEST = "UPDATE_WORKINGDAYS_REQUEST";
export const UPDATE_WORKINGDAYS_SUCCESS = "UPDATE_WORKINGDAYS_SUCCESS";
export const UPDATE_WORKINGDAYS_FAILURE = "UPDATE_WORKINGDAYS_FAILURE";

export const GET_ONE_WORKINGDAYS_REQUEST = "GET_ONE_WORKINGDAYS_REQUEST";
export const GET_ONE_WORKINGDAYS_SUCCESS = "GET_ONE_WORKINGDAYS_SUCCESS";
export const GET_ONE_WORKINGDAYS_FAILURE = "GET_ONE_WORKINGDAYS_FAILURE";