export const ADD_SUB_GROUPID_REQUEST = "ADD_SUB_GROUPID_REQUEST";
export const ADD_SUB_GROUPID_SUCCESS = "ADD_SUB_GROUPID_SUCCESS";
export const ADD_SUB_GROUPID_FAILURE = "ADD_SUB_GROUPID_FAILURE";

export const GET_SUB_GROUPID_REQUEST = "GET_SUB_GROUPID_REQUEST";
export const GET_SUB_GROUPID_SUCCESS = "GET_SUB_GROUPID_SUCCESS";
export const GET_SUB_GROUPID_FAILURE = "GET_SUB_GROUPID_FAILURE";

export const UPDATE_SUB_GROUPID_REQUEST = "UPDATE_SUB_GROUPID_REQUEST";
export const UPDATE_SUB_GROUPID_SUCCESS = "UPDATE_SUB_GROUPID_SUCCESS";
export const UPDATE_SUB_GROUPID_FAILURE = "UPDATE_SUB_GROUPID_FAILURE";

export const GET_ONE_SUB_GROUPID_REQUEST = "GET_ONE_SUB_GROUPID_REQUEST";
export const GET_ONE_SUB_GROUPID_SUCCESS = "GET_ONE_SUB_GROUPID_SUCCESS";
export const GET_ONE_SUB_GROUPID_FAILURE = "GET_ONE_SUB_GROUPID_FAILURE";
