export const ADD_LECTURERTIMETABLE_REQUEST = "ADD_LECTURERTIMETABLE_REQUEST";
export const ADD_LECTURERTIMETABLE_SUCCESS = "ADD_LECTURERTIMETABLE_SUCCESS";
export const ADD_LECTURERTIMETABLE_FAILURE = "ADD_LECTURERTIMETABLE_FAILURE";

export const GET_LECTURERTIMETABLE_REQUEST = "GET_LECTURERTIMETABLE_REQUEST";
export const GET_LECTURERTIMETABLE_SUCCESS = "GET_LECTURERTIMETABLE_SUCCESS";
export const GET_LECTURERTIMETABLE_FAILURE = "GET_LECTURERTIMETABLE_FAILURE";
