export const ADD_BUILDING_REQUEST = "ADD_BUILDING_REQUEST";
export const ADD_BUILDING_SUCCESS = "ADD_BUILDING_SUCCESS";
export const ADD_BUILDING_FAILURE = "ADD_BUILDING_FAILURE";

export const GET_BUILDING_REQUEST = "GET_BUILDING_REQUEST";
export const GET_BUILDING_SUCCESS = "GET_BUILDING_SUCCESS";
export const GET_BUILDING_FAILURE = "GET_BUILDING_FAILURE";

export const UPDATE_BUILDING_REQUEST = "UPDATE_BUILDING_REQUEST";
export const UPDATE_BUILDING_SUCCESS = "UPDATE_BUILDING_SUCCESS";
export const UPDATE_BUILDING_FAILURE = "UPDATE_YEAR_SEMISTER_FAILURE";

export const GET_ONE_BUILDING_REQUEST = "GET_ONE_BUILDING_REQUEST";
export const GET_ONE_BUILDING_SUCCESS = "GET_ONE_BUILDING_SUCCESS";
export const GET_ONE_BUILDING_FAILURE = "GET_ONE_BUILDING_FAILURE";
