export const ADD_STUDENTTIMETABLE_REQUEST = "ADD_STUDENTTIMETABLE_REQUEST";
export const ADD_STUDENTTIMETABLE_SUCCESS = "ADD_STUDENTTIMETABLE_SUCCESS";
export const ADD_STUDENTTIMETABLE_FAILURE = "ADD_STUDENTTIMETABLE_FAILURE";

export const GET_STUDENTTIMETABLE_REQUEST = "GET_STUDENTTIMETABLE_REQUEST";
export const GET_STUDENTTIMETABLE_SUCCESS = "GET_STUDENTTIMETABLE_SUCCESS";
export const GET_STUDENTTIMETABLE_FAILURE = "GET_STUDENTTIMETABLE_FAILURE";
