export const ADD_PROGRAMME_REQUEST = "ADD_PROGRAMME_REQUEST";
export const ADD_PROGRAMME_SUCCESS = "ADD_PROGRAMME_SUCCESS";
export const ADD_PROGRAMME_FAILURE = "ADD_PROGRAMME_FAILURE";

export const GET_PROGRAMME_REQUEST = "GET_PROGRAMME_REQUEST";
export const GET_PROGRAMME_SUCCESS = "GET_PROGRAMME_SUCCESS";
export const GET_PROGRAMME_FAILURE = "GET_PROGRAMME_FAILURE";

export const UPDATE_PROGRAMME_REQUEST = "UPDATE_PROGRAMME_REQUEST";
export const UPDATE_PROGRAMME_SUCCESS = "UPDATE_PROGRAMME_SUCCESS";
export const UPDATE_PROGRAMME_FAILURE = "UPDATE_PROGRAMME_FAILURE";

export const GET_ONE_PROGRAMME_REQUEST = "GET_ONE_PROGRAMME_REQUEST";
export const GET_ONE_PROGRAMME_SUCCESS = "GET_ONE_PROGRAMME_SUCCESS";
export const GET_ONE_PROGRAMME_FAILURE = "GET_ONE_PROGRAMME_FAILURE";
