export const ADD_SUBJECT_REQUEST="ADD_SUBJECT_REQUEST";
export const ADD_SUBJECT_SUCCESS="ADD_SUBJECT_SUCCESS";
export const ADD_SUBJECT_FAILURE="ADD_SUBJECT_FAILURE";

// export const GET_SUBJECT_REQUEST = "GET_SUBJECT_REQUEST";
// export const GET_SUBJECT_SUCCESS = "GET_SUBJECT_SUCCESS";
// export const GET_SUBJECT_FAILURE = "GET_SUBJECT_FAILURE";