export const ADD_GEN_SUBGROUPID_REQUEST = "ADD_GEN_SUBGROUPID_REQUEST";
export const ADD_GEN_SUBGROUPID_SUCCESS = "ADD_GEN_SUBGROUPID_SUCCESS";
export const ADD_GEN_SUBGROUPID_FAILURE = "ADD_GEN_SUBGROUPID_FAILURE";

export const GET_GEN_SUBGROUPID_REQUEST = "GET_GEN_SUBGROUPID_REQUEST";
export const GET_GEN_SUBGROUPID_SUCCESS = "GET_GEN_SUBGROUPID_SUCCESS";
export const GET_GEN_SUBGROUPID_FAILURE = "GET_GEN_SUBGROUPID_FAILURE";
